config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'projects#index'
  resources :comments
  resources :projects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

# Model for comments
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_one :event, as: :eventable, dependent: :destroy
end

app/models/event.rb
# frozen_string_literal: true

# Model for polymorphic Event association
class Event < ApplicationRecord
  belongs_to :eventable, polymorphic: true
  belongs_to :project
end

app/models/project.rb
# frozen_string_literal: true

# Model for Projects
class Project < ApplicationRecord
  has_many :transitions, class_name: 'ProjectTransition', autosave: false, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :comments, through: :events, source: :eventable, source_type: 'Comment'

  include Statesman::Adapters::ActiveRecordQueries[
    transition_class: ProjectTransition,
    initial_state: :draft
  ]

  # Initialize the state machine
  def state_machine
    @state_machine ||= ProjectStateMachine.new(self, transition_class: ProjectTransition,
                                                     association_name: :transitions)
  end

  # Optionally delegate some methods

  delegate :can_transition_to?,
           :current_state, :history, :last_transition, :last_transition_to,
           :transition_to!, :transition_to, :in_state?, to: :state_machine
end

app/models/project_state_machine.rb
# frozen_string_literal: true

# Statesman state machine definition for Project
class ProjectStateMachine
  include Statesman::Machine

  state :draft, initial: true
  state :active
  state :cancelled
  state :complete
  state :on_hold

  transition from: :draft,     to: %i[active cancelled on_hold]
  transition from: :active,    to: %i[draft cancelled complete on_hold]
  transition from: :cancelled, to: :draft
  transition from: :complete,  to: :active
  transition from: :on_hold,   to: %i[draft active cancelled complete]

  after_transition do |project, transition|
    Event.new(project: project, eventable: transition).save
  end
end

app/models/project_transition.rb
# frozen_string_literal: true

# Statesman Transition model linked to Project
class ProjectTransition < ApplicationRecord
  # include Statesman::Adapters::ActiveRecordTransition

  # If your transition table doesn't have the default `updated_at` timestamp column,
  # you'll need to configure the `updated_timestamp_column` option, setting it to
  # another column name (e.g. `:updated_on`) or `nil`.
  #
  # self.updated_timestamp_column = :updated_on
  # self.updated_timestamp_column = nil

  belongs_to :project, inverse_of: :transitions
  has_one :event, as: :eventable, dependent: :destroy

  after_destroy :update_most_recent, if: :most_recent?

  private

  def update_most_recent
    last_transition = project.transitions.order(:sort_key).last
    return if last_transition.blank?

    last_transition.most_recent = true
    last_transition.save
  end
end

app/models/user.rb
# frozen_string_literal: true

# Devise User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Controller for Comments
class CommentsController < ApplicationController
  before_action :authenticate_user!

  # GET /comments or /comments.json
  def index
    redirect_to projects_path, notice: 'Unauthorised page'
  end

  # GET /comments/1 or /comments/1.json
  def show
    redirect_to projects_path, notice: 'Unauthorised page'
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    redirect_to projects_path, notice: 'Unauthorised page'
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    project = Project.find(comment_params[:project_id])

    respond_to do |format|
      if @comment.save
        Event.new(project: project, eventable: @comment).save
        format.html { redirect_to project_url(project), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: project }
      else
        format.html { render :show, status: :unprocessable_entity, location: project }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    redirect_to projects_path, notice: 'Unauthorised page'
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    redirect_to projects_path, notice: 'Unauthorised page'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:user_id, :text, :project_id)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Projects controller
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = Project.includes(:events, :comments, :transitions).find(params[:id])
    @comment = Comment.new()
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params.except(:current_state))
        unless project_params[:current_state] == @project.current_state
          @project.transition_to!(project_params[:current_state])
        end
        format.html { redirect_to project_url(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:title, :current_state)
  end
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= comment.project_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.number_field :project_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeyTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand text-light" href="/projects">Home</a>
      </div>
    </nav>
    <div class="container text-center"><%= yield %></div>
  </body>
</html>

app/views/projects/_comment.html.erb
<tr>
  <td>Comment</td>
  <td><%= event.created_at %></td>
  <td><%= event.eventable.text %></td>
  <td>Author: <%= event.eventable.user.email %></td>
</tr>

app/views/projects/_comment_form.html.erb
<%= form_with(model: comment) do |form| %>
  <h2>Add comment</h2>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <%= form.hidden_field :project_id, value: project.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_edit_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.select(:current_state, project.state_machine.allowed_transitions.unshift(project.current_state)) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

</div>

app/views/projects/_projecttransition.html.erb
<tr>
  <td>State Change</td>
  <td><%= event.created_at %></td>
  <td><%= event.eventable.to_state %></td>
  <td></td>
</tr>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "edit_form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.current_state %></td>
          <td>
            <%= link_to "Show", project %>
          </td>
          <td>
            <%= link_to "Edit", edit_project_path(project) %>
          </td>
          <td>
            <%= link_to 'Delete', project_path(project), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @project.title %></h1>
<h2>Status: <%= @project.current_state.capitalize %></h2>

<div>
  <%= link_to "Edit", edit_project_path(@project) %> |
  <%= link_to 'Delete', project_path(@project), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
</div>

<h2>Conversation</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Type</th>
      <th scope="col">Timestamp</th>
      <th scope="col">Detail</th>
      <th scope="col">Additional Information</th>
    </tr>
  </thead>
  <tbody>
    <% @project.events.each do |event| %>
      <%= render event.eventable_type.downcase, event: event %>
    <% end %>
  </tbody>
</table>

<%= render "comment_form", project: @project, comment: @comment %>